-- Create damage_reports table
create table damage_reports (
  id bigint generated by default as identity primary key,
  report_id text unique not null,
  property_type text not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  address text not null,
  damage_date date not null,
  damage_assessment jsonb not null,
  insurance_claim boolean not null default false,
  contact_consent boolean not null default false,
  image_urls text[] not null default '{}',
  receipt_urls text[] not null default '{}',
  storm_reports jsonb not null default '[]',
  created_at timestamp with time zone not null default now()
);

-- Create RLS policies
alter table damage_reports enable row level security;

-- Allow anonymous users to insert new reports
create policy "Allow anonymous insert"
  on damage_reports for insert
  with check (true);

-- Allow anonymous users to select their own reports
create policy "Allow anonymous select"
  on damage_reports for select
  using (true);